### ISSUE TITLE
Did LiteOn kill the LTST-A683CEGBW?

### ISSUE THREAD

**Issue by jnz86** [sszczep/kicad-libraries#1]
Global stock seems to be limited to one broker in Europe with 1700 of them, but no hits anywhere else. Mouser and Digikey don't even recognize it as a part number they could buy. It's not so new it shouldn't exist, and the larger 5050 sized part is everywhere. I suppose the only difference for you is the footprint and clearances. But I wasn't sure if you had any idea why this part seems to have vanished.

**Comment by sszczep** [comment]
Just checked and you are completely right. Gonna replace them anytime soon ;)

**Comment by sszczep** [comment]
Well, it's been some time now. I couldn't find any alternatives. Please, if you find something let me know and I'll make appropriate changes. I'll ask liteon about these leds and let you know.

**Comment by sszczep** [comment]
LiteOn told me that they don't have the exact replacement. 

SK6812Mini-E looks promising. It's dimension and pin-to-pin compatible with the LTST. I will try them out once they arrive.

**Comment by dentex** [comment]
Hello,
are the LTST-A683CEGBW compatible with the WS2812B? (I mean, can the same arduino library be used?)
thanks

**Comment by sszczep** [comment]
Yes, you can use the same library. I don’t have a footprint for them though
